### ISSUE TITLE
Docker won't build container.

### ISSUE THREAD

**Issue by reihe00** [Stannieman/audacity-with-asio-builder#5]
Hello,
i am new to docker and i have an issue. The script doesn't do anything and i get this error:

Starting Docker container to build Audacity with ASIO support
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: hcsshim::PrepareLayer - failed failed in Win32: Unzulässige Funktion. (0x1).

Any idea what i can do?

WinVer: 1903 - 18362.295
Docker: 2.1.0.3

**Comment by Stannieman** [comment]
It seems you are hitting this issue: https://github.com/microsoft/hcsshim/issues/624
So not something I can fix unfortunately, but you may try to install the latest updates for Windows (apparently a fix in both dockerd and Windows are needed).

But please note that you don't need to build the image yourself in order to use it.
I built it and pushed it to Docker Hub (https://cloud.docker.com/u/stannieman/repository/docker/stannieman/audacity-with-asio-builder) so you can just pull that one.
So actually BuildAudacity.ps1 is the only script you need, everything inside Dockerpath is just for me.

**Comment by reihe00** [comment]
Pulling the image didn't work either but i was able to fix the problem by finding a CBFS driver on my system and deleting it.

**Comment by scyto** [comment]
Thanks, this pointed me in the right direction - there was a hidden device in device manager called StorLib bus (virtual storage support) disabling that device fixed all.

I have no idea what installed it.
