### ISSUE TITLE
Custom Audacity Widgets version

### ISSUE THREAD

**Issue by micsthepick** [Stannieman/audacity-with-asio-builder#9]
Audacity uses it's own fork of wxWidgets at https://github.com/audacity/wxWidgets, so it probably should use this fork in the docker script

**Comment by Stannieman** [comment]
You seem to be right.
Though I swear I read somewhere a long time ago that they got rid of the dependency on that patch and moved to the regular one...
But I can't find that anymore so I'll create a new version this week that uses the custom version.

**Comment by Stannieman** [comment]
Quick heads up about my local changes:
* Using custom WxWidgets is done.
* Adding --dns to docker run command is done.
* Fixing that typo PlatformTraget => PlatformTarget from your PR is done.
* Now uses Git to clone Audacity and WxWidgets source, because zipped patched WxWidgets doesn't include submodules so we need git anyway.
* Switched to built in tar.exe to extract zip files (gets rid of 7zip dependency). Just like 7zip this is muuuuch faster than Expand-Archive.

It seems they switched to CMake for the Windows build for 2.4.2, so now figuring that out. I have used CMake before for building other software on Linux so I don't expect too much troubles there.

**Comment by Stannieman** [comment]
Ok here we go:
* Stuck with 2.4.1 atm. That CMake build doesn't work that easily (it suddenly also requires Jack to be installed? That thing has no way of installing without GUI??). But apparently ASIO is temporarily disabled in 2.4.2, so there's anyway no need to have it working now.

All other stuff is fixed in 1.4.0.

**Comment by micsthepick** [comment]
there is a patch that fixes the ASIO build for 2.4.2, but the version is essentially bug fixes, and future versions won't need the patch, and I've managed to get it to build myself, so I will not be asking for you to implement that patch.
